# Generated by Django 3.0.3 on 2020-02-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('sunrise', models.TimeField(null=True)),
                ('sunset', models.TimeField(null=True)),
                ('feed', models.TimeField(null=True)),
            ],
        ),
    ]
